[wokwi]
version = 1
firmware = '.pio/build/FlowIOS3Wokwi/wokwi-merged.bin'
elf = '.pio/build/FlowIOS3Wokwi/firmware.elf'
chips = ["wokwi/ads1115.chip.json","wokwi/tca9554pwr.chip.json"]

[[wifi]]
ssid = "Wokwi-GUEST"
password = ""
internet = true

[[net.forward]]
from = "localhost:8080"
to = "target:80"

[[chip]]
name = "ads1115"
binary = "wokwi/ads1115.chip.wasm"


[[chip]]
name = "bme680"
binary = "wokwi/bme680.chip.wasm"

[[chip]]
name = "tca9554pwr"
binary = "wokwi/tca9554pwr.chip.wasm"
