#pragma once

#include "App/BuildFlags.h"

#if FLOW_BUILD_IS_FLOWIO
#define FEATURE_WIFI 1
#define FEATURE_TIME 1
#define FEATURE_MQTT 1
#define FEATURE_HA 1
#define FEATURE_IO 1
#define FEATURE_POOL_DEVICE 1
#define FEATURE_POOL_LOGIC 1
#define FEATURE_HMI 1
#define FEATURE_SUPERVISOR_HMI 0
#define FEATURE_WEB 0
#define FEATURE_FW_UPDATE 0
#define FEATURE_I2C_CFG_SERVER 1
#define FEATURE_I2C_CFG_CLIENT 0
#define FEATURE_WIFI_PROVISIONING 0
#endif

#if FLOW_BUILD_IS_SUPERVISOR
#define FEATURE_WIFI 1
#define FEATURE_TIME 1
#define FEATURE_MQTT 0
#define FEATURE_HA 0
#define FEATURE_IO 0
#define FEATURE_POOL_DEVICE 0
#define FEATURE_POOL_LOGIC 0
#define FEATURE_HMI 0
#define FEATURE_SUPERVISOR_HMI 1
#define FEATURE_WEB 1
#define FEATURE_FW_UPDATE 1
#define FEATURE_I2C_CFG_SERVER 0
#define FEATURE_I2C_CFG_CLIENT 1
#define FEATURE_WIFI_PROVISIONING 1
#endif

