# Generate runtime UI manifest and compact Supervisor lookup header.

import json
import os
import re
from pathlib import Path

Import = type("Import", (), {})

try:
    Import("env")  # type: ignore
except Exception:
    env = None


def _get_project_dir():
    if env is not None:
        try:
            return env.get("PROJECT_DIR")
        except Exception:
            pass
    return os.getcwd()


def _find_runtime_ui_files(modules_root: Path):
    return sorted(modules_root.rglob("*RuntimeUi.json"))


def _parse_module_ids(module_id_path: Path):
    text = module_id_path.read_text(encoding="utf-8")

    enum_match = re.search(r"enum class ModuleId\s*:\s*uint8_t\s*\{(?P<body>.*?)\};", text, re.S)
    if not enum_match:
        raise RuntimeError("Unable to locate ModuleId enum")

    names = []
    for raw_line in enum_match.group("body").splitlines():
        line = raw_line.split("//", 1)[0].strip()
        if not line:
            continue
        if line.endswith(","):
            line = line[:-1].strip()
        if not line:
            continue
        if "=" in line:
            line = line.split("=", 1)[0].strip()
        names.append(line)

    numeric_by_name = {}
    for index, name in enumerate(names):
        numeric_by_name[name] = index

    alias_by_name = {}
    for match in re.finditer(r'case\s+ModuleId::([A-Za-z_][A-Za-z0-9_]*)\s*:\s*return\s+"([^"]+)";', text):
        alias_by_name[match.group(1)] = match.group(2)

    alias_to_numeric = {}
    for name, numeric in numeric_by_name.items():
        alias = alias_by_name.get(name)
        if alias:
            alias_to_numeric[alias] = numeric

    return numeric_by_name, alias_by_name, alias_to_numeric


def _resolve_module_id(raw_value, numeric_by_name, alias_to_numeric):
    if isinstance(raw_value, int):
        return raw_value
    if not isinstance(raw_value, str):
        raise RuntimeError(f"Invalid moduleId value: {raw_value!r}")

    if raw_value in numeric_by_name:
        return numeric_by_name[raw_value]
    if raw_value in alias_to_numeric:
        return alias_to_numeric[raw_value]
    raise RuntimeError(f"Unknown moduleId reference: {raw_value}")


def _json_dump(path: Path, payload):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")


def _c_string(text):
    if not text:
        return "nullptr"
    raw = text.encode("utf-8")
    out = '"'
    for byte in raw:
        ch = chr(byte)
        if ch == "\\":
            out += "\\\\"
        elif ch == '"':
            out += '\\"'
        elif 32 <= byte <= 126:
            out += ch
        else:
            # Use fixed-width octal escapes to avoid C/C++ `\xNN...` greediness.
            out += f"\\{byte:03o}"
    out += '"'
    return out


def _write_header(out_path: Path, entries):
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        f.write("#pragma once\n")
        f.write("/**\n")
        f.write(" * @file RuntimeUiManifest_Generated.h\n")
        f.write(" * @brief Auto-generated compact runtime UI manifest lookup for Supervisor.\n")
        f.write(" */\n\n")
        f.write("// This file is generated by scripts/generate_runtimeui_manifest.py\n")
        f.write("// Do not edit manually.\n\n")
        f.write('#include "Core/RuntimeUi.h"\n\n')
        f.write("struct RuntimeUiManifestItem {\n")
        f.write("    RuntimeUiId id;\n")
        f.write("    const char* key;\n")
        f.write("    const char* type;\n")
        f.write("    const char* unit;\n")
        f.write("};\n\n")
        f.write("inline constexpr RuntimeUiManifestItem kRuntimeUiManifestItems[] = {\n")
        for entry in entries:
            f.write(
                "    {"
                f"{entry['id']}, "
                f"{_c_string(entry['key'])}, "
                f"{_c_string(entry['type'])}, "
                f"{_c_string(entry.get('unit') or '')}"
                "},\n"
            )
        f.write("};\n\n")
        f.write(
            "inline constexpr size_t kRuntimeUiManifestItemCount = "
            "(sizeof(kRuntimeUiManifestItems) / sizeof(kRuntimeUiManifestItems[0]));\n\n"
        )
        f.write("inline constexpr const RuntimeUiManifestItem* findRuntimeUiManifestItem(RuntimeUiId id)\n")
        f.write("{\n")
        f.write("    for (size_t i = 0; i < kRuntimeUiManifestItemCount; ++i) {\n")
        f.write("        if (kRuntimeUiManifestItems[i].id == id) return &kRuntimeUiManifestItems[i];\n")
        f.write("    }\n")
        f.write("    return nullptr;\n")
        f.write("}\n")


def main():
    project_dir = Path(_get_project_dir())
    modules_root = project_dir / "src" / "Modules"
    module_id_path = project_dir / "src" / "Core" / "ModuleId.h"
    out_json_path = project_dir / "data" / "webinterface" / "runtimeui.json"
    out_header_path = project_dir / "src" / "Core" / "Generated" / "RuntimeUiManifest_Generated.h"

    numeric_by_name, alias_by_name, alias_to_numeric = _parse_module_ids(module_id_path)

    entries = []
    seen_runtime_ids = {}

    for path in _find_runtime_ui_files(modules_root):
        payload = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(payload, dict):
            raise RuntimeError(f"RuntimeUi file must contain an object: {path}")

        module_ref = payload.get("moduleId")
        module_numeric = _resolve_module_id(module_ref, numeric_by_name, alias_to_numeric)
        module_name = None
        for name, numeric in numeric_by_name.items():
            if numeric == module_numeric:
                module_name = name
                break
        if module_name is None or module_name in ("Unknown", "Count"):
            raise RuntimeError(f"Invalid runtime UI module id in {path}: {module_ref}")

        module_alias = alias_by_name.get(module_name, "unknown")
        values = payload.get("values")
        if not isinstance(values, list):
            raise RuntimeError(f"RuntimeUi file missing values array: {path}")

        for value in values:
            if not isinstance(value, dict):
                raise RuntimeError(f"RuntimeUi value entry must be an object: {path}")

            value_id = value.get("valueId")
            if not isinstance(value_id, int) or value_id <= 0 or value_id >= 100:
                raise RuntimeError(f"Invalid valueId in {path}: {value_id!r}")

            runtime_id = module_numeric * 100 + value_id
            declared_runtime_id = value.get("runtimeId")
            if declared_runtime_id is not None and declared_runtime_id != runtime_id:
                raise RuntimeError(
                    f"runtimeId mismatch in {path}: declared={declared_runtime_id} expected={runtime_id}"
                )

            if runtime_id in seen_runtime_ids:
                raise RuntimeError(
                    f"Duplicate runtimeId {runtime_id} in {path} and {seen_runtime_ids[runtime_id]}"
                )
            seen_runtime_ids[runtime_id] = path

            display = value.get("display")
            if display is not None:
                if display == "gauge":
                    display = "circ-gauge"
                if display not in ("circ-gauge", "horiz-gauge", "badge", "boolean", "time", "value", "flags"):
                    raise RuntimeError(f"Invalid display in {path}: {display!r}")
            else:
                value_type = value.get("type")
                if value_type == "bool":
                    display = "boolean"
                else:
                    display = "value"

            display_config = value.get("displayConfig")
            if display_config is not None and not isinstance(display_config, dict):
                raise RuntimeError(f"displayConfig must be an object in {path}: {display_config!r}")

            entry = {
                "id": runtime_id,
                "runtimeId": runtime_id,
                "moduleId": module_numeric,
                "module": module_alias,
                "valueId": value_id,
                "key": value["key"],
                "label": value["label"],
                "type": value["type"],
                "domain": value["domain"],
                "group": value.get("group"),
                "unit": value.get("unit"),
                "decimals": value.get("decimals"),
                "order": value.get("order"),
                "enum": value.get("enum"),
                "flags": value.get("flags"),
                "display": display,
                "displayConfig": display_config,
            }
            entries.append(entry)

    entries.sort(key=lambda item: (item["domain"], item.get("group") or "", item.get("order") or 0, item["id"]))
    manifest = {
        "ok": True,
        "values": entries,
    }
    _json_dump(out_json_path, manifest)
    _write_header(out_header_path, entries)


main()
